const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.Dictionary,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.System.Exps.max,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Audio: 0},
	{ArrDataRandomType: 0},
	{ArrDataRandomTypeColor: 0},
	{LocalStorage: 0},
	{DicData: 0},
	{uid_cell: 0},
	{uid_big: 0},
	{is_block_big_chid: 0},
	{time_destroy: 0},
	{block: 0},
	{num_block_create_big: 0},
	{is_blocks_big: 0},
	{is_destroy: 0},
	{block_big_1: 0},
	{block_big_2: 0},
	{block_big_3: 0},
	{block_suggestion: 0},
	{block_black: 0},
	{block_light: 0},
	{order_group: 0},
	{block_template: 0},
	{is_selected: 0},
	{type_color: 0},
	{order_check: 0},
	{angle_rotate: 0},
	{Blocks_check: 0},
	{Blocks_test: 0},
	{is_block_drag: 0},
	{is_suggestion: 0},
	{width_original: 0},
	{height_original: 0},
	{order_block_drag: 0},
	{rotate_list: 0},
	{type_block: 0},
	{is_valid_check: 0},
	{order_group_check: 0},
	{angle_group_check: 0},
	{is_disable: 0},
	{numBlocksRow: 0},
	{numBlocksCol: 0},
	{size_x: 0},
	{size_y: 0},
	{data: 0},
	{group_blocks_1: 0},
	{group_blocks_10: 0},
	{group_blocks_11: 0},
	{group_blocks_12: 0},
	{group_blocks_2: 0},
	{group_blocks_3: 0},
	{group_blocks_4: 0},
	{group_blocks_5: 0},
	{group_blocks_6: 0},
	{group_blocks_7: 0},
	{group_blocks_8: 0},
	{group_blocks_9: 0},
	{group_blocks_check_collision: 0},
	{group_blocks_suggestion_destroy: 0},
	{order_set_group: 0},
	{group_random: 0},
	{set_blocks_drag: 0},
	{fragment1: 0},
	{fragment2: 0},
	{fragment3: 0},
	{fragment4: 0},
	{fragment5: 0},
	{BestCup: 0},
	{Tween: 0},
	{bigLight: 0},
	{BGGame: 0},
	{btnAudio: 0},
	{btnHome: 0},
	{row: 0},
	{col: 0},
	{value: 0},
	{is_have_block_destroy: 0},
	{cell: 0},
	{dingbar: 0},
	{bgScore: 0},
	{map: 0},
	{popup_no_move: 0},
	{star: 0},
	{txt_no_moves: 0},
	{txt_score: 0},
	{Fade: 0},
	{txt_score_extra: 0},
	{txt_scoreBest: 0},
	{BestScore: 0},
	{btnRestart: 0},
	{popup_gameover: 0},
	{bgGameOver: 0},
	{txt_scoreBest_lose: 0},
	{logo: 0},
	{btnPlayHome: 0},
	{Rotate: 0},
	{BlocksDragFamily: 0},
	{MoveTo: 0},
	{Physics: 0},
	{DestroyOutsideLayout: 0},
	{FragmentsFamily: 0},
	{BlocksBigFamily: 0},
	{orderDragSelected: 0},
	{widthCell: 0},
	{heigthCell: 0},
	{numRows: 0},
	{numCols: 0},
	{isAllowDrag: 0},
	{score: 0},
	{cost_score_place_block: 0},
	{cost_score_destroy_block: 0},
	{x: 0},
	{y: 0},
	{score_extra: 0},
	{type: 0},
	{type_color_block: 0},
	{is_valid: 0},
	{count: 0},
	{uid_block: 0},
	{group_type: 0},
	{is_game_end: 0},
	{angle_current_valid: 0},
	{index_rand: 0},
	{val_rand: 0},
	{type_color2: 0},
	{x_set: 0},
	{y_set: 0},
	{num_cell: 0},
	{x_min: 0},
	{x_max: 0},
	{y_min: 0},
	{y_max: 0},
	{is_spawn: 0},
	{type_block_1: 0},
	{type_block_2: 0},
	{type_block_3: 0},
	{type_block_4: 0},
	{uid: 0},
	{distance_nearest: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	ArrDataRandomType: class extends self.IArrayInstance {},
	ArrDataRandomTypeColor: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	DicData: class extends self.IDictionaryInstance {},
	block: class extends self.ISpriteInstance {},
	block_big_1: class extends self.ISpriteInstance {},
	block_big_2: class extends self.ISpriteInstance {},
	block_big_3: class extends self.ISpriteInstance {},
	block_suggestion: class extends self.ISpriteInstance {},
	block_black: class extends self.ISpriteInstance {},
	block_light: class extends self.ISpriteInstance {},
	block_template: class extends self.ISpriteInstance {},
	Blocks_check: class extends self.ISpriteInstance {},
	Blocks_test: class extends self.ISpriteInstance {},
	group_blocks_1: class extends self.ISpriteInstance {},
	group_blocks_10: class extends self.ISpriteInstance {},
	group_blocks_11: class extends self.ISpriteInstance {},
	group_blocks_12: class extends self.ISpriteInstance {},
	group_blocks_2: class extends self.ISpriteInstance {},
	group_blocks_3: class extends self.ISpriteInstance {},
	group_blocks_4: class extends self.ISpriteInstance {},
	group_blocks_5: class extends self.ISpriteInstance {},
	group_blocks_6: class extends self.ISpriteInstance {},
	group_blocks_7: class extends self.ISpriteInstance {},
	group_blocks_8: class extends self.ISpriteInstance {},
	group_blocks_9: class extends self.ISpriteInstance {},
	group_blocks_check_collision: class extends self.ISpriteInstance {},
	group_blocks_suggestion_destroy: class extends self.ISpriteInstance {},
	set_blocks_drag: class extends self.ISpriteInstance {},
	fragment1: class extends self.ISpriteInstance {},
	fragment2: class extends self.ISpriteInstance {},
	fragment3: class extends self.ISpriteInstance {},
	fragment4: class extends self.ISpriteInstance {},
	fragment5: class extends self.ISpriteInstance {},
	BestCup: class extends self.ISpriteInstance {},
	bigLight: class extends self.ISpriteInstance {},
	BGGame: class extends self.ISpriteInstance {},
	btnAudio: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	cell: class extends self.ISpriteInstance {},
	dingbar: class extends self.ISpriteInstance {},
	bgScore: class extends self.ISpriteInstance {},
	map: class extends self.ISpriteInstance {},
	popup_no_move: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	txt_no_moves: class extends self.ISpriteFontInstance {},
	txt_score: class extends self.ISpriteFontInstance {},
	txt_score_extra: class extends self.ISpriteFontInstance {},
	txt_scoreBest: class extends self.ISpriteFontInstance {},
	BestScore: class extends self.ISpriteInstance {},
	btnRestart: class extends self.ISpriteInstance {},
	popup_gameover: class extends self.ISpriteInstance {},
	bgGameOver: class extends self.ISpriteInstance {},
	txt_scoreBest_lose: class extends self.ISpriteFontInstance {},
	logo: class extends self.ISpriteInstance {},
	btnPlayHome: class extends self.ISpriteInstance {},
	BlocksDragFamily: class extends self.ISpriteInstance {},
	FragmentsFamily: class extends self.ISpriteInstance {},
	BlocksBigFamily: class extends self.ISpriteInstance {}
}